const API='https://pokeapi.co/api/v2/';
const TYPE_COLORS={bug:'#26de81',dragon:'#ffeaa7',electric:'#fed330',fairy:'#FF0069',fighting:'#30336b',fire:'#f0932b',flying:'#81ecec',grass:'#00b894',ground:'#EFB549',ghost:'#a55eea',ice:'#74b9ff',normal:'#95afc0',poison:'#6c5ce7',psychic:'#a29bfe',rock:'#2d3436',water:'#0190FF'};
const TYPES=Object.keys(TYPE_COLORS);
const PAGES=[...document.querySelectorAll('.page')];
const $=id=>document.getElementById(id);
const STORE_KEY='pokemonLabStateV3';
let cache=new Map();
let state=loadState();

function loadState(){try{return Object.assign({user:null,users:{},collection:{},favorites:[],shiny:[],recent:[],mysteryHistory:[],mysteryStreak:0,battleHistory:[],quiz:{score:0,correct:0,wrong:0,streak:0,best:0,xp:0},xp:0,level:1,avatar:'⚡',theme:'light',team:[],trainerName:'PokéTrainer',daily:{}},JSON.parse(localStorage.getItem(STORE_KEY)||'{}'));}catch{return {user:null,users:{},collection:{},favorites:[],shiny:[],recent:[],mysteryHistory:[],mysteryStreak:0,battleHistory:[],quiz:{score:0,correct:0,wrong:0,streak:0,best:0,xp:0},xp:0,level:1,avatar:'⚡',theme:'light',team:[],trainerName:'PokéTrainer',daily:{}}}}
function save(){localStorage.setItem(STORE_KEY,JSON.stringify(state));renderProgress();}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function img(p){return p?.sprites?.other?.['official-artwork']?.front_default||p?.sprites?.other?.dream_world?.front_default||p?.sprites?.front_default||''}
function title(n){return String(n||'').replace(/-/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}
function toast(msg,type='ok'){const root=$('toastRoot');if(!root)return;const el=document.createElement('div');el.className=`toast ${type}`;el.innerHTML=`<i class="fa-solid ${type==='error'?'fa-circle-exclamation':'fa-circle-check'}"></i>${esc(msg)}`;root.appendChild(el);setTimeout(()=>el.remove(),2600)}
function showLoader(text='Loading Pokémon data…'){const l=$('appLoader');if(!l)return;l.classList.remove('hidden');const s=l.querySelector('strong');if(s)s.textContent=text;}
function hideLoader(){$('appLoader')?.classList.add('hidden')}
function skeleton(container,count=4){if(!container)return;container.innerHTML=Array.from({length:count},()=>'<div class="skeleton-card"><div class="sk-img"></div><div class="sk-line"></div><div class="sk-line short"></div></div>').join('')}
async function api(path){if(cache.has(path))return cache.get(path);const r=await fetch(API+path);if(!r.ok)throw Error(`Request failed (${r.status})`);const d=await r.json();cache.set(path,d);return d}
async function pokemon(q){const key=String(q).toLowerCase().trim();if(!key)throw Error('Enter a Pokémon name or ID');return api(`pokemon/${encodeURIComponent(key)}`)}
function typesHTML(p){return (p.types||[]).map(x=>`<span style="background:${TYPE_COLORS[x.type.name]||'#777'}">${esc(x.type.name)}</span>`).join('')}
function card(p,opts={}){const collected=!!state.collection[p.id];const fav=state.favorites.includes(p.id);const shiny=state.shiny.includes(p.id);return `<article class="pokemon-card" data-id="${p.id}" style="background:radial-gradient(circle at 50% 0%,${TYPE_COLORS[p.types?.[0]?.type?.name]||'#95afc0'} 36%,#fff 36%)"><p class="hp"><span>HP</span> ${p.stats?.[0]?.base_stat??'—'}</p><img src="${img(p)}" alt="${esc(title(p.name))}" loading="lazy"><h2 class="poke-name">${esc(title(p.name))}</h2><div class="types">${typesHTML(p)}</div><div class="stats"><div><h3>${p.stats?.[1]?.base_stat??'—'}</h3><p>Attack</p></div><div><h3>${p.stats?.[2]?.base_stat??'—'}</h3><p>Defense</p></div><div><h3>${p.stats?.[5]?.base_stat??'—'}</h3><p>Speed</p></div></div><div class="card-actions"><button class="card-action" data-info="${p.id}" title="Info"><i class="fa-solid fa-circle-info"></i></button><button class="card-action ${fav?'selected':''}" data-fav="${p.id}" title="Favorite"><i class="fa-solid fa-heart"></i></button><button class="card-action ${shiny?'selected':''}" data-shiny="${p.id}" title="Shiny collected"><i class="fa-solid fa-star"></i></button><button class="btn small ${collected?'success':''}" data-collect="${p.id}">${collected?'✓ Collected':'+ Collection'}</button></div></article>`}
function renderCards(container,list){if(!container)return;if(!list?.length){container.innerHTML='<div class="empty-state"><i class="fa-solid fa-box-open"></i><h3>No Pokémon found</h3><p>Try another search or filter.</p></div>';return}container.innerHTML=list.map(p=>card(p)).join('')}
function addRecent(p){state.recent=[p.id,...state.recent.filter(x=>x!==p.id)].slice(0,10);save()}
function addCollection(p){if(!state.collection[p.id]){state.collection[p.id]={id:p.id,name:p.name,added:Date.now()};awardXP(10);toast(`${title(p.name)} added to your collection`)}else toast(`${title(p.name)} is already collected`);save();renderCollection();renderPokemonResult(p)}
function removeCollection(id){delete state.collection[id];save();renderCollection();toast('Removed from collection')}
function toggleFavorite(id){const i=state.favorites.indexOf(Number(id));if(i<0){state.favorites.push(Number(id));toast('Added to Favorites')}else{state.favorites.splice(i,1);toast('Removed from Favorites')}save();renderCollection();renderFavorites();renderPokemonResult(currentPokemon?.data)}
function toggleShiny(id){const n=Number(id),i=state.shiny.indexOf(n);if(i<0){state.shiny.push(n);toast('Marked as shiny collected')}else{state.shiny.splice(i,1);toast('Removed from shiny collection')}save();renderCollection();renderShiny()}
function awardXP(n){state.xp+=n;while(state.xp>=state.level*100){state.xp-=state.level*100;state.level++;toast(`Level up! You are now Level ${state.level}`)}state.quiz.xp=(state.quiz.xp||0)+n;save()}
function renderProgress(){const count=Object.keys(state.collection).length,total=1025,p=Math.min(100,count/total*100);const ids=['homeProgressCount','homeProgressPct','sideProgressText'];$(ids[0])&&($(ids[0]).textContent=`${count} / ${total}`);$(ids[1])&&($(ids[1]).textContent=`${p.toFixed(1)}%`);$('homeProgressBar')&&($('homeProgressBar').style.width=p+'%');$('homeProgressRing')&&($('homeProgressRing').style.setProperty('--progress',p));$('sideProgressText')&&($('sideProgressText').textContent=`${count} / ${total}`);$('sideProgressBar')&&($('sideProgressBar').style.width=p+'%');$('homeTrainerName')&&($('homeTrainerName').textContent=state.trainerName);$('trainerName')&&($('trainerName').textContent=state.trainerName);$('trainerAvatar')&&($('trainerAvatar').textContent=state.avatar);}
function page(name){PAGES.forEach(p=>p.classList.toggle('active',p.id===`page-${name}`));document.querySelectorAll('.nav-link[data-page]').forEach(n=>n.classList.toggle('active',n.dataset.page===name));document.querySelectorAll('.nav-group').forEach(g=>{if(g.querySelector(`.nav-link[data-page="${name}"]`))g.classList.add('open')});window.scrollTo({top:0,behavior:'smooth'});if(name==='collection')renderCollection();if(name==='favorites')renderFavorites();if(name==='shiny')renderShiny();if(name==='trainer')renderTrainer();if(name==='analytics')renderAnalytics();if(name==='achievements')renderAchievements();if(name==='battleHistory')renderBattleHistory();if(name==='quiz')loadQuiz();if(name==='mystery')renderMysteryHistory();if(name==='regions')renderRegions();if(name==='daily')renderDaily();if(name==='pokedex')renderPokedexHome();if(name==='type')renderTypeHome()}

// navigation dropdowns + links
document.querySelectorAll('.nav-group-toggle').forEach(b=>b.addEventListener('click',()=>b.closest('.nav-group').classList.toggle('open')));
document.addEventListener('click',e=>{const n=e.target.closest('[data-page]');if(n&&n.dataset.page){page(n.dataset.page);$('sidebar')?.classList.remove('mobile-open');$('sidebarOverlay')?.classList.remove('show')}});
$('mobileMenu')?.addEventListener('click',()=>{$('sidebar')?.classList.add('mobile-open');$('sidebarOverlay')?.classList.add('show')});$('sidebarClose')?.addEventListener('click',()=>{$('sidebar')?.classList.remove('mobile-open');$('sidebarOverlay')?.classList.remove('show')});$('sidebarOverlay')?.addEventListener('click',()=>{$('sidebar')?.classList.remove('mobile-open');$('sidebarOverlay')?.classList.remove('show')});

// auth
document.querySelectorAll('.auth-tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.auth-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('loginForm')?.classList.toggle('hidden',b.dataset.auth!=='login');$('registerForm')?.classList.toggle('hidden',b.dataset.auth!=='register')}));
function showApp(){if(!$('authView'))return;$('authView').classList.add('hidden');$('appShell').classList.remove('hidden');renderProgress();loadHome();hideLoader()}
$('registerForm')?.addEventListener('submit',e=>{e.preventDefault();const email=$('registerEmail').value.trim().toLowerCase();if(state.users[email])return toast('Account already exists','error');state.users[email]={name:$('registerName').value.trim()||'PokéTrainer',password:$('registerPassword').value};state.user=email;state.trainerName=state.users[email].name;save();showApp();toast('Trainer account created')});
$('loginForm')?.addEventListener('submit',e=>{e.preventDefault();const email=$('loginEmail').value.trim().toLowerCase(),u=state.users[email];if(!u||u.password!==$('loginPassword').value)return toast('Invalid trainer credentials','error');state.user=email;state.trainerName=u.name;save();showApp();toast('Welcome back, Trainer')});
$('logoutBtn')?.addEventListener('click',()=>{state.user=null;save();$('appShell').classList.add('hidden');$('authView').classList.remove('hidden')});
$('quickProfile')?.addEventListener('click',()=>page('trainer'));$('trainerChip')?.addEventListener('click',()=>page('trainer'));
document.querySelectorAll('[data-toggle-password]').forEach(b=>b.addEventListener('click',()=>{const i=$(b.dataset.togglePassword.slice(1));i.type=i.type==='password'?'text':'password'}));

// theme — keep earlier UI palette, only switch surfaces/text
function applyTheme(){const t=state.theme==='system'?(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'):state.theme;document.documentElement.dataset.theme=t;$('themeBtn')?.setAttribute('title',`Theme: ${state.theme[0].toUpperCase()+state.theme.slice(1)}`)}
$('themeBtn')?.addEventListener('click',()=>{state.theme=state.theme==='light'?'dark':state.theme==='dark'?'system':'light';save();applyTheme();toast(`Theme: ${state.theme}`)});applyTheme();matchMedia('(prefers-color-scheme:dark)').addEventListener?.('change',applyTheme);

// search
let currentPokemon={data:null};
async function searchPokedex(q,container=$('pokedexResult')){if(!q?.trim()){renderPokedexHome();return}container.innerHTML='<div class="loading"><div class="pokeball-loader small"><i></i></div><h3>Loading Pokémon…</h3></div>';try{const p=await pokemon(q);currentPokemon.data=p;addRecent(p);renderPokemonResult(p,container)}catch(e){container.innerHTML='<div class="error"><h3>Pokémon not found</h3><p>Check the name or Pokédex number and try again.</p><button class="btn ghost" onclick="renderPokedexHome()">Retry</button></div>'}}
function renderPokemonResult(p,container=$('pokedexResult')){if(!p||!container)return;container.innerHTML=`<div class="pokemon-detail"><div class="detail-art"><span>#${String(p.id).padStart(4,'0')}</span><img src="${img(p)}" alt="${esc(title(p.name))}"></div><div class="detail-copy"><div class="detail-actions"><button class="btn primary" data-collect="${p.id}">${state.collection[p.id]?'✓ Collected':'+ Add to Collection'}</button><button class="icon-btn ${state.favorites.includes(p.id)?'selected':''}" data-fav="${p.id}"><i class="fa-solid fa-heart"></i></button></div><span class="eyebrow">POKÉDEX #${p.id}</span><h2>${esc(title(p.name))}</h2><div class="types">${typesHTML(p)}</div><p>Height ${(p.height/10).toFixed(1)} m · Weight ${(p.weight/10).toFixed(1)} kg</p><div class="detail-stats">${p.stats.map(s=>`<div><span>${esc(s.stat.name.replace('special-','Sp. '))}</span><b>${s.base_stat}</b><i><em style="width:${Math.min(100,s.base_stat/2)}%"></em></i></div>`).join('')}</div><button class="btn ghost" data-info="${p.id}"><i class="fa-solid fa-dna"></i> View Info / Evolution</button></div></div>`}
$('pokemonSearchBtn')?.addEventListener('click',()=>searchPokedex($('pokemonSearch').value));$('pokemonSearch')?.addEventListener('keydown',e=>e.key==='Enter'&&searchPokedex($('pokemonSearch').value));
document.querySelectorAll('[data-search]').forEach(b=>b.addEventListener('click',()=>{page('pokedex');$('pokemonSearch').value=b.dataset.search;searchPokedex(b.dataset.search)}));
$('globalSearch')?.addEventListener('keydown',e=>{if(e.key==='Enter'){const q=e.target.value.trim();if(q){page('pokedex');$('pokemonSearch').value=q;searchPokedex(q);e.target.value=''}}});

// type search — ALL pokemon
function buildTypes(){const box=$('typeButtons');if(!box)return;box.innerHTML=TYPES.map(t=>`<button class="type-button" data-type="${t}" style="--type:${TYPE_COLORS[t]}">${title(t)}</button>`).join('');box.querySelectorAll('[data-type]').forEach(b=>b.addEventListener('click',()=>searchType(b.dataset.type)))}
async function searchType(t){const box=$('typeResult')||$('typeCards');if(!box)return;const label=$('selectedType');if(label)label.textContent=`${title(t)} Pokémon`;box.innerHTML='<div class="loading"><div class="pokeball-loader small"><i></i></div><h3>Loading all Pokémon…</h3></div>';try{const d=await api(`type/${t}`);const ids=d.pokemon.map(x=>Number(x.pokemon.url.split('/').filter(Boolean).pop())).filter(Boolean).sort((a,b)=>a-b);const list=[];for(let i=0;i<ids.length;i+=12){const chunk=await Promise.all(ids.slice(i,i+12).map(id=>pokemon(id)));list.push(...chunk);box.innerHTML=`<div class="type-loading"><div class="pokeball-loader small"><i></i></div><span>Loaded ${list.length} of ${ids.length}…</span></div>`;box.parentElement?.querySelector('.type-loading')?.scrollIntoView?.({block:'nearest'});}renderCards(box,list)}catch(e){box.innerHTML='<div class="error"><h3>Could not load this type</h3><p>Please retry when PokéAPI is available.</p></div>'}}

// card global actions
document.addEventListener('click',async e=>{const c=e.target.closest('[data-collect]');if(c){try{const p=await pokemon(c.dataset.collect);addCollection(p)}catch{toast('Could not load Pokémon','error')}}const f=e.target.closest('[data-fav]');if(f)toggleFavorite(f.dataset.fav);const s=e.target.closest('[data-shiny]');if(s)toggleShiny(s.dataset.shiny);const inf=e.target.closest('[data-info]');if(inf){try{openInfo(await pokemon(inf.dataset.info))}catch{toast('Could not open info','error')}}});

// info/evolution
async function openInfo(p){const root=$('infoResult');if(!root)return;page('info');root.innerHTML='<div class="loading"><div class="pokeball-loader small"><i></i></div><h3>Building evolution chain…</h3></div>';try{const species=await api(`pokemon-species/${p.id}`),chain=await api(species.evolution_chain.url.replace(API,''));const nodes=[];function walk(n){nodes.push(n.species.name);(n.evolves_to||[]).forEach(walk)}walk(chain.chain);const ps=await Promise.all(nodes.map(pokemon));root.innerHTML=`<div class="info-hero"><img src="${img(p)}"><div><span class="eyebrow">#${p.id} / POKÉMON INFO</span><h2>${title(p.name)}</h2><div class="types">${typesHTML(p)}</div><p>Abilities: ${p.abilities.map(a=>title(a.ability.name)).join(', ')}</p></div></div><div class="evolution-panel"><div class="section-head"><h3>Evolution Family</h3></div><div class="evolution-chain">${ps.map((x,i)=>`<button class="evo-node ${x.id===p.id?'current':''}" data-info="${x.id}"><img src="${img(x)}"><b>${title(x.name)}</b><small>#${x.id}</small></button>${i<ps.length-1?'<span class="evo-arrow">→</span>':''}`).join('')}</div></div>`}catch{root.innerHTML='<div class="error"><h3>Evolution data unavailable</h3><p>Try again with another Pokémon.</p></div>'}}
$('infoSearchBtn')?.addEventListener('click',()=>searchPokedex($('infoSearch').value,$('infoResult')));$('infoSearch')?.addEventListener('keydown',e=>e.key==='Enter'&&searchPokedex(e.target.value,$('infoResult')));

// collection
async function renderCollection(){const grid=$('collectionGrid');if(!grid)return;const entries=Object.values(state.collection);$('collectionStats').innerHTML=`<div><b>${entries.length}</b><span>Collected</span></div><div><b>${state.favorites.length}</b><span>Favorites</span></div><div><b>${state.shiny.length}</b><span>Shiny</span></div>`;if(!entries.length){grid.innerHTML='<div class="empty-state"><i class="fa-solid fa-box-open"></i><h3>Your collection is empty</h3><p>Search a Pokémon and use Add to Collection.</p><button class="btn primary" data-page="pokedex">Explore Pokédex</button></div>';return}const q=($('collectionSearch')?.value||'').toLowerCase();const filter=$('collectionFilter')?.value||'all';const sort=$('collectionSort')?.value||'id';let ids=entries.filter(x=>!q||x.name.includes(q));if(filter==='favorite')ids=ids.filter(x=>state.favorites.includes(x.id));if(filter==='shiny')ids=ids.filter(x=>state.shiny.includes(x.id));if(filter==='legendary')ids=ids.filter(x=>x.id>=144&&x.id<=151||x.id>=243&&x.id<=251);ids.sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='recent'?b.added-a.added:a.id-b.id);skeleton(grid,Math.min(4,ids.length));try{const ps=await Promise.all(ids.map(x=>pokemon(x.id)));renderCards(grid,ps)}catch{grid.innerHTML='<div class="error"><h3>Collection data could not load</h3><p>Retry with an internet connection.</p></div>'}}
['collectionSearch','collectionFilter','collectionSort'].forEach(id=>$(id)?.addEventListener('input',renderCollection));$('collectionClear')?.addEventListener('click',()=>{if(confirm('Clear your entire collection?')){state.collection={};save();renderCollection()}});
async function renderFavorites(){const g=$('favoriteGrid');if(!g)return;const ps=await Promise.all(state.favorites.map(id=>pokemon(id)).catch?[]:[]);}
async function renderFavGeneric(id,ids){const g=$(id);if(!g)return;if(!ids.length){g.innerHTML='<div class="empty-state"><i class="fa-solid fa-heart"></i><h3>Nothing here yet</h3><p>Use the heart button on a Pokémon.</p></div>';return}skeleton(g,Math.min(4,ids.length));try{renderCards(g,await Promise.all(ids.map(pokemon)))}catch{g.innerHTML='<div class="error">Could not load saved Pokémon.</div>'}}
renderFavorites=()=>renderFavGeneric('favoriteGrid',state.favorites);renderShiny=()=>{const g=$('shinyGrid');if($('shinyStats'))$('shinyStats').textContent=`${state.shiny.length} shiny Pokémon collected`;return renderFavGeneric('shinyGrid',state.shiny)};

// home
async function loadHome(){renderProgress();const r=$('recentHome');if(!r)return;const ids=state.recent.length?state.recent:[25,6,133];try{renderCards(r,await Promise.all(ids.slice(0,6).map(pokemon)))}catch{r.innerHTML='<div class="empty-state">Recent Pokémon unavailable.</div>'}}
function renderPokedexHome(){const r=$('pokedexResult');if(r&&!r.innerHTML.trim())r.innerHTML='<div class="empty-state"><i class="fa-solid fa-book-open"></i><h3>Search the Pokédex</h3><p>Try Pikachu, Charizard, Eevee or a Pokédex number.</p></div>'}
function renderTypeHome(){buildTypes();const r=$('typeResult');if(r&&!r.innerHTML.trim())r.innerHTML='<div class="empty-state"><i class="fa-solid fa-layer-group"></i><h3>Choose a type</h3><p>Select a type to load every Pokémon in it.</p></div>'}

// mystery
function renderMysteryHistory(){const g=$('mysteryHistory');if(!g)return;g.innerHTML=state.mysteryHistory.length?state.mysteryHistory.slice(0,6).map(x=>`<button class="history-item" data-info="${x.id}"><img src="${x.image}" alt="${esc(x.name)}"><span>${title(x.name)}</span><small>${new Date(x.time).toLocaleDateString()}</small></button>`).join(''):'<div class="empty-state compact"><i class="fa-solid fa-clock-rotate-left"></i><p>No recent reveals yet.</p></div>';if($('mysteryStreak'))$('mysteryStreak').textContent=state.mysteryStreak}
async function mystery(){const btn=$('mysteryBtn');btn.disabled=true;btn.innerHTML='<span class="pokeball-loader tiny"><i></i></span> Drawing…';$('mysteryCard')?.classList.remove('revealed');try{const p=await pokemon(Math.floor(Math.random()*151)+1);const rarity=p.id===150||p.id===151?'Legendary/Mythical':p.id%10===0?'Rare':'Common';$('mysteryFront').innerHTML=`<div class="mystery-rarity">${rarity}</div><img class="mystery-img" src="${img(p)}" alt="${title(p.name)}"><h3>${title(p.name)}</h3><div class="types">${typesHTML(p)}</div><div class="mystery-stats"><div><strong>${p.stats[0].base_stat}</strong><small>HP</small></div><div><strong>${p.stats[1].base_stat}</strong><small>ATK</small></div><div><strong>${p.stats[2].base_stat}</strong><small>DEF</small></div><div><strong>${p.stats[5].base_stat}</strong><small>SPD</small></div></div><button class="btn small" data-collect="${p.id}">+ Collection</button>`;$('mysteryCard').classList.add('revealed');state.mysteryHistory=[{id:p.id,name:p.name,image:img(p),time:Date.now()},...state.mysteryHistory.filter(x=>x.id!==p.id)].slice(0,8);state.mysteryStreak++;awardXP(15);save();renderMysteryHistory();}catch{toast('Mystery card could not be loaded','error')}finally{btn.disabled=false;btn.innerHTML='<i class="fa-solid fa-wand-magic-sparkles"></i> Draw Another Card'}}
$('mysteryBtn')?.addEventListener('click',mystery);$('clearMystery')?.addEventListener('click',()=>{state.mysteryHistory=[];state.mysteryStreak=0;save();renderMysteryHistory()});

// battle simplified turn simulator
let battleState=null;
async function startBattle(){const a=$('battleOne').value,b=$('battleTwo').value;if(!a||!b)return toast('Enter both Pokémon','error');const arena=$('battleArena');arena.innerHTML='<div class="loading"><div class="pokeball-loader small"><i></i></div><h3>Loading battle…</h3></div>';try{const [p1,p2]=await Promise.all([pokemon(a),pokemon(b)]);battleState={p1,p2,hp1:p1.stats[0].base_stat,hp2:p2.stats[0].base_stat,max1:p1.stats[0].base_stat,max2:p2.stats[0].base_stat,turn:1};renderBattle()}catch(e){arena.innerHTML=`<div class="error"><h3>Battle setup failed</h3><p>${esc(e.message)}</p></div>`}}
function renderBattle(){const s=battleState,damage=Math.max(5,Math.floor(s.p1.stats[1].base_stat*.12));$('battleArena').innerHTML=`<div class="battle-fighters"><div class="fighter"><span class="fighter-label">YOUR POKÉMON</span><img src="${img(s.p1)}"><h2>${title(s.p1.name)}</h2><div class="types">${typesHTML(s.p1)}</div><div class="hpbar"><i style="width:${Math.max(0,s.hp1/s.max1*100)}%"></i></div><small>${Math.max(0,s.hp1)} / ${s.max1} HP</small></div><div class="battle-vs">VS</div><div class="fighter"><span class="fighter-label">OPPONENT</span><img src="${img(s.p2)}"><h2>${title(s.p2.name)}</h2><div class="types">${typesHTML(s.p2)}</div><div class="hpbar"><i style="width:${Math.max(0,s.hp2/s.max2*100)}%"></i></div><small>${Math.max(0,s.hp2)} / ${s.max2} HP</small></div></div><div class="battle-controls"><button class="btn primary" id="attackBtn"><i class="fa-solid fa-bolt"></i> Attack</button><div class="battle-log" id="battleLog">Turn ${s.turn}: Choose your move.</div></div>`;$('attackBtn').onclick=()=>{if(s.hp2<=0||s.hp1<=0)return;const d=Math.max(5,Math.floor((s.p1.stats[1].base_stat/3)*(0.8+Math.random()*.4)));s.hp2=Math.max(0,s.hp2-d);let log=`${title(s.p1.name)} dealt ${d} damage.`;if(s.hp2>0){const d2=Math.max(4,Math.floor((s.p2.stats[1].base_stat/3)*(0.7+Math.random()*.4)));s.hp1=Math.max(0,s.hp1-d2);log+=` ${title(s.p2.name)} dealt ${d2} damage.`}else{log+=` ${title(s.p1.name)} wins!`;state.battleHistory.unshift({a:s.p1.name,b:s.p2.name,winner:s.p1.name,time:Date.now()});awardXP(30);save()}s.turn++;renderBattle();$('battleLog').textContent=log}}
$('startBattle')?.addEventListener('click',startBattle);$('resetBattle')?.addEventListener('click',()=>{$('battleArena').innerHTML='';battleState=null});
function renderBattleHistory(){const g=$('battleHistoryList');if(!g)return;g.innerHTML=state.battleHistory.length?state.battleHistory.slice(0,20).map(x=>`<div class="history-card"><b>${title(x.a)}</b> vs <b>${title(x.b)}</b><span>Winner: ${title(x.winner)}</span><small>${new Date(x.time).toLocaleString()}</small></div>`).join(''):'<div class="empty-state"><h3>No battles yet</h3></div>'}$('clearBattleHistory')?.addEventListener('click',()=>{state.battleHistory=[];save();renderBattleHistory()});

// quiz with visible score
let quizAnswer=null,quizMode='silhouette';
async function loadQuiz(){const shell=$('quizShell');if(!shell)return;renderQuizScore();shell.innerHTML='<div class="loading"><div class="pokeball-loader small"><i></i></div><h3>Preparing quiz…</h3></div>';try{const id=Math.floor(Math.random()*151)+1,p=await pokemon(id);quizAnswer=p;shell.innerHTML=`<div class="quiz-score"><div>Score <b>${state.quiz.score}</b></div><div>Streak <b>${state.quiz.streak}</b></div><div>Best <b>${state.quiz.best}</b></div></div><div class="quiz-card"><img class="quiz-img ${quizMode==='silhouette'?'silhouette':''}" src="${img(p)}" alt="Mystery Pokémon"><h3>${quizMode==='silhouette'?'Who is this Pokémon?':`Which Pokémon is ${quizMode==='type'?p.types.map(t=>t.type.name).join(' / '):'shown here'}?`}</h3><div class="quiz-options">${quizOptions(p).map(x=>`<button class="quiz-option" data-answer="${x.id}">${title(x.name)}</button>`).join('')}</div></div>`;shell.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>answerQuiz(Number(b.dataset.answer)));}catch{shell.innerHTML='<div class="error">Quiz data unavailable.</div>'}}
async function quizOptions(p){const ids=new Set([p.id]);while(ids.size<4)ids.add(Math.floor(Math.random()*151)+1);const others=await Promise.all([...ids].map(id=>pokemon(id)));return others.sort(()=>Math.random()-.5)}
function renderQuizScore(){const q=state.quiz;const el=document.querySelector('#page-quiz .page-head');if(el&&!el.querySelector('.quiz-score-head'))el.insertAdjacentHTML('beforeend',`<div class="quiz-score-head"><span>Score <b>${q.score}</b></span><span>Streak <b>${q.streak}</b></span><span>Best <b>${q.best}</b></span></div>`)}
async function answerQuiz(id){if(!quizAnswer)return;const correct=id===quizAnswer.id;if(correct){state.quiz.score+=10;state.quiz.correct++;state.quiz.streak++;state.quiz.best=Math.max(state.quiz.best,state.quiz.streak);awardXP(10);toast('Correct! +10 points')}else{state.quiz.wrong++;state.quiz.streak=0;toast(`Incorrect — it was ${title(quizAnswer.name)}`,'error')}save();loadQuiz()}
document.querySelectorAll('[data-quizmode]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-quizmode]').forEach(x=>x.classList.remove('active'));b.classList.add('active');quizMode=b.dataset.quizmode;loadQuiz()}));

// calculators
$('statCalc')?.addEventListener('click',async()=>{const r=$('statResult');r.innerHTML='<div class="loading"><div class="pokeball-loader small"><i></i></div></div>';try{const p=await pokemon($('statPokemon').value),level=Math.max(1,Math.min(100,Number($('statLevel').value)||50));r.innerHTML=`<div class="calculator-result-inner"><h3>${title(p.name)} — Level ${level}</h3>${p.stats.map(s=>{const v=Math.floor(s.base_stat*level/100)+5;return `<div class="calc-stat"><span>${title(s.stat.name)}</span><b>${v}</b><i><em style="width:${Math.min(100,v/2)}%"></em></i></div>`}).join('')}</div>`}catch{r.innerHTML='<div class="error">Could not calculate this Pokémon.</div>'}});
$('damageCalc')?.addEventListener('click',async()=>{const r=$('damageResult');r.innerHTML='<div class="loading"><div class="pokeball-loader small"><i></i></div></div>';try{const a=await pokemon($('dmgAttacker').value),d=await pokemon($('dmgDefender').value),power=Number($('dmgPower').value)||60,level=Number($('dmgLevel').value)||50,damage=Math.max(1,Math.floor((((2*level/5+2)*power*a.stats[1].base_stat/Math.max(1,d.stats[2].base_stat))/50)+2));r.innerHTML=`<div class="calculator-result-inner"><h3>Estimated Damage</h3><strong class="damage-number">${damage}</strong><p>Approx. ${Math.min(100,damage/d.stats[0].base_stat*100).toFixed(1)}% of ${title(d.name)} HP. This is a simplified estimate.</p></div>`}catch{r.innerHTML='<div class="error">Enter valid attacker and defender Pokémon.</div>'}});

// profile / analytics
function renderTrainer(){const c=$('trainerPageContent');if(!c)return;const next=state.level*100;c.innerHTML=`<div class="profile-card"><div class="profile-avatar">${state.avatar}</div><div><h2>${esc(state.trainerName)}</h2><p>Pokémon Lab Trainer</p><button class="btn ghost" id="editTrainer">Edit trainer name</button></div></div><div class="level-card"><div class="level-top"><span>LEVEL</span><strong>${state.level}</strong></div><div class="level-progress"><i style="width:${Math.min(100,state.xp/next*100)}%"></i></div><p>${state.xp} / ${next} XP to Level ${state.level+1}</p></div><div class="milestones"><div class="section-head"><h3>Milestones</h3></div><div class="milestone-grid"><div>🎯 <b>${Object.keys(state.collection).length}</b><small>Pokémon collected</small></div><div>💖 <b>${state.favorites.length}</b><small>Favorites</small></div><div>✨ <b>${state.shiny.length}</b><small>Shiny</small></div><div>⚔️ <b>${state.battleHistory.length}</b><small>Battles recorded</small></div></div></div><div class="avatar-options"><h3>Profile avatar</h3><div>${['⚡','🔥','💧','🌿','👑','🎮','🧪','⭐'].map(a=>`<button class="avatar-choice ${a===state.avatar?'selected':''}" data-avatar="${a}">${a}</button>`).join('')}<label class="avatar-upload">＋<input id="avatarUpload" type="file" accept="image/*" hidden></label></div></div>`;$('editTrainer').onclick=()=>{const name=prompt('Trainer name',state.trainerName);if(name?.trim()){state.trainerName=name.trim();if(state.user&&state.users[state.user])state.users[state.user].name=state.trainerName;save();renderTrainer();toast('Trainer name updated')}};c.querySelectorAll('[data-avatar]').forEach(b=>b.onclick=()=>{state.avatar=b.dataset.avatar;save();renderTrainer()});$('avatarUpload').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{state.avatar=r.result;save();renderTrainer()};r.readAsDataURL(f)}}
function renderAnalytics(){const c=$('analyticsContent');if(!c)return;const byType={};state.recent.forEach(()=>{});c.innerHTML=`<div class="analytics-grid"><div class="analytics-card"><b>${Object.keys(state.collection).length}</b><span>Collected</span></div><div class="analytics-card"><b>${state.favorites.length}</b><span>Favorites</span></div><div class="analytics-card"><b>${state.shiny.length}</b><span>Shiny</span></div><div class="analytics-card"><b>${state.battleHistory.length}</b><span>Battles</span></div></div><div class="analysis-panel"><h3>Research Activity</h3><div class="analysis-bars"><div><span>Collection</span><i style="width:${Math.min(100,Object.keys(state.collection).length/10)}%"></i></div><div><span>Discovery</span><i style="width:${Math.min(100,state.recent.length*10)}%"></i></div><div><span>Quiz Score</span><i style="width:${Math.min(100,state.quiz.score)}%"></i></div></div></div>`}
function renderAchievements(){const g=$('achievementGrid');if(!g)return;const a=[['FIRST DISCOVERY',state.recent.length>=1],['COLLECTOR',Object.keys(state.collection).length>=25],['SUPER COLLECTOR',Object.keys(state.collection).length>=100],['SHINY HUNTER',state.shiny.length>=5],['BATTLE READY',state.battleHistory.length>=1],['QUIZ MASTER',state.quiz.best>=10]];g.innerHTML=a.map(x=>`<div class="achievement ${x[1]?'unlocked':''}"><i class="fa-solid fa-trophy"></i><div><b>${x[0]}</b><small>${x[1]?'Unlocked':'Locked'}</small></div></div>`).join('')}
function renderRegions(){const g=$('regionsGrid');if(!g||g.children.length)return;const rs=[['Kanto',1,151],['Johto',152,251],['Hoenn',252,386],['Sinnoh',387,493],['Unova',494,649],['Kalos',650,721],['Alola',722,809],['Galar',810,898],['Paldea',899,1025]];g.innerHTML=rs.map(r=>`<button class="region-card" data-region="${r[1]}-${r[2]}"><span>GEN</span><b>${r[0]}</b><small>#${r[1]}–#${r[2]}</small></button>`).join('')}
function renderDaily(){const c=$('dailyChallenge');if(!c)return;const key=new Date().toISOString().slice(0,10);if(state.daily.date!==key)state.daily={date:key,done:false};c.innerHTML=`<div class="daily-card"><span class="eyebrow">TODAY'S CHALLENGE</span><h2>Add a Pokémon to your collection</h2><p>Discover a Pokémon and add it today.</p><button class="btn primary" data-page="pokedex">Find Pokémon</button><span class="daily-status">${state.daily.done?'✓ Completed':'In progress'}</span></div>`}

// initial UI
buildTypes();renderProgress();renderMysteryHistory();loadHome();
if(state.user){showApp()}else{$('appLoader')?.classList.add('hidden');$('authView')?.classList.remove('hidden');$('appShell')?.classList.add('hidden')}
window.renderPokedexHome=renderPokedexHome;
